config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :page, only: [:new, :create, :edit, :update, :destroy, :show]

  get '/:id', to: 'page#show', as: :page_show
  root to: 'page#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :slug, uniqueness: { case_sensitive: false }
  validates :title, :description, :slug, :h1, :content, :priority, length: { minimum: 1 }

  validates :published_at, presence: true
  validates :priority, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def index
    Time.zone = 'Europe/Minsk'
    @per_page = params[:limit] || 5
    @pages=Page.all.order(priority: :desc).where("published_at <= :start_date",
                                                 {start_date: Time.zone.now})
    .paginate(:page => params[:page], :per_page => @per_page)

    @not_published = Page.all.order(priority: :desc).where("published_at > :start_date",
                                                           {start_date: Time.zone.now})
  end


  def show
    @page = Page.find_by(slug: params[:id])
        if(@page.nil?)
          redirect_to root_path
        end
  end

  def edit
    @page = Page.find_by(slug: params[:id])
    if(@page.nil?)
      redirect_to root_path
    end
  end


  def create
    req = params[:page]
    if(!req[:published_at_date].empty? && !req[:published_at_hour].empty?)
      date = Date.strptime(req[:published_at_date])
      time = Time.parse(req[:published_at_hour])

      t = date.year.to_s + "." + date.month.to_s + "." + date.day.to_s + " " + time.hour.to_s +
      ":" + time.min.to_s + ":" + time.sec.to_s

      Time.zone = 'Europe/Minsk'
      newdate = Time.zone.parse(t)

    end

    @page = Page.new(
        title: req[:title],
        description: req[:description],
        slug: req[:slug],
        h1: req[:h1],
        content: req[:content],
        published_at: newdate,
        priority: req[:priority]
    )
    if @page.save()
      redirect_to page_show_path(@page[:slug])
    else
      flash.now[:error] = @page.errors.full_messages
      render :action => 'new'
    end
  end


  def update
    req = params[:page]
    @page = Page.find(params[:id])
    if(!req[:published_at_date].empty? && !req[:published_at_hour].empty?)
      date = Date.strptime(req[:published_at_date])
      time = Time.parse(req[:published_at_hour])
      t = date.year.to_s + "." + date.month.to_s + "." + date.day.to_s + " " + time.hour.to_s +
         ":" + time.min.to_s + ":" + time.sec.to_s
      p (t)
    Time.zone = 'Europe/Minsk'
    newdate = Time.zone.parse(t)
    end

    if @page.update(
        title: req[:title],
        description: req[:description],
        slug: req[:slug],
        h1: req[:h1],
        content: req[:content],
        published_at: newdate,
        priority: req[:priority]
    )
      redirect_to @page
    else
      render 'edit'
    end
  end


  def destroy
    @page = Page.find_by(id: params[:id])
    if(@page.nil?)
      redirect_to root_path
    else
      @page.destroy
    end
    redirect_to root_path

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <meta name="description" content="<%= yield :description %>">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/edit.html.erb
<%= render "partials/header" %>


<%= form_with(model: @page, local: true, html:{class:"col-md-8 offset-md-2"}) do |form| %>
    <% @page[:published_at].nil? ? datetime=nil : datetime= DateTime.parse(@page[:published_at].to_s)%>
    <% datetime.nil? ? newdate = nil : newdate = Date.new(datetime.year,datetime.month, datetime.day) %>
    <% datetime.nil? ? newtime = nil : newtime = datetime.strftime("%k:%M:%S") %>

    <h1>Editing page</h1>

    <% if @page.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@page.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @page.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group row">
      <%= form.label :title , class:"col-sm-2 col-form-label"%>
      <%= form.text_field :title, class:"col-sm-3 form-control", placeholder:"Title" %>
    </div>

    <div class="form-group row">
      <%= form.label :description, class:"col-sm-2 col-form-label" %>
      <%= form.text_field :description, class:"col-sm-3 form-control", placeholder:"Description in meta tag" %>
    </div>

    <div class="form-group row">
      <%= form.label :slug, class:"col-sm-2 col-form-label"%><br>
      <%= form.text_field :slug, class:"col-sm-3 form-control", placeholder:"URL" %>
    </div>

    <div class="form-group row">
      <%= form.label :h1, class:"col-sm-2 col-form-label"%><br>
      <%= form.text_field :h1, class:"col-sm-3 form-control", placeholder:"Article title" %>
    </div>

    <div class="form-group">
      <%= form.label :content, class:"col-sm-2 col-form-label" %>
      <%= form.text_area :content, class:"form-control", id:"editor", rows:"10" %>
    </div>

    <div class="form-group">
      <%= form.label :published_at %><br>
      <div class="form-group row">
        <%= form.label :Date, class:"col-sm-1 col-form-label"%><br>
        <%= form.text_field :published_at_date, data: {provide: 'datepicker'},value:newdate, class:"datepicker col-sm-3 form-control", placeholder:"yyyy-mm-dd"%>
        <%= form.label :Time, class:"col-sm-1 col-form-label"%><br>
        <%= form.text_field :published_at_hour, class:"col-sm-2 form-control", value:newtime, placeholder:"hh:mm:ss"%>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :priority, class:"col-sm-1 col-form-label"%><br>
      <%= form.text_field :priority, class:"col-sm-2 form-control" %>
    </div>

    <div class="row">
      <div class="col-sm-1"><%= form.submit 'Save', class:"btn btn-primary " %></div>
      <br/>
      <%= link_to 'Cancel', :back, class:"btn btn-warning"%>
    </div>


<% end %>

app/views/page/index.html.erb
<%= render "partials/header" %>

<table class="table table-bordered table-hover table-sm col-md-10 offset-md-1">
  <thead>
    <tr>
      <th colspan="11">Published pages</th>
    </tr>
    <tr>
      <th>id</th>
      <th >Title</th>
      <th >Description</th>
      <th >Slug</th>
      <th >H1</th>
      <th >Content</th>
      <th >Published at</th>
      <th >Priority</th>
      <th >Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td> <%= page[:id] %></td>
        <td> <%= page.title.first(15) %> </td>
        <td> <%= page.description.first(10) %> </td>
        <td> <%= page.slug.first(10) %> </td>
        <td> <%= page.h1.first(5) %> </td>
        <td> <%= page.content.first(20) %> </td>
        <td> <%= page.published_at %> </td>
        <td> <%= page.priority %> </td>
        <td>
          <%= link_to page_show_path(page[:slug]) do%>
              <button type="button" class="btn btn-outline-primary btn-sm">Show</button>
          <% end %>
        </td>
        <td>
          <%= link_to edit_page_path(page[:slug]) do%>
              <button type="button" class="btn btn-outline-warning btn-sm">Edit</button>
          <% end %>
        </td>

        <td>
          <%= link_to page_path(page) ,method: :delete,data: { confirm: 'Are you sure?' } do %>
              <button type="button" class="btn btn-outline-danger btn-sm">Delete</button>
          <% end %>
        </td>
      </tr>

  <% end %>
  </tbody>
</table>

<div class="pagination-bloc">
  <%= will_paginate @pages, class:'pagination-lg'%>

  <div class="per_page">
    <%= select_tag :limit, options_for_select([5,10,20,50], params[:limit].to_i),
                   :onchange => "if(this.value){window.location='?limit='+this.value;}" %>
    <span>per page</span>
  </div>

</div>


<button type="button" id="unpublished" class="btn btn-info col-md-10 offset-md-1">Not published pages</button>
<table class="table table-bordered table-hover table-sm col-md-10 offset-md-1 hidden" id="np">
  <thead>
  <tr>
    <th colspan="11">Not published pages</th>
  </tr>
  <tr>
    <th>id</th>
    <th >Title</th>
    <th >Description</th>
    <th >Slug</th>
    <th >H1</th>
    <th >Content</th>
    <th >Published at</th>
    <th >Priority</th>
    <th >Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  </thead>
  <tbody>
  <% @not_published.each do |page| %>
      <tr>
        <td> <%= page[:id] %></td>
        <td> <%= page.title.first(15) %> </td>
        <td> <%= page.description.first(10) %> </td>
        <td> <%= page.slug.first(10) %> </td>
        <td> <%= page.h1.first(5) %> </td>
        <td> <%= page.content.first(20) %> </td>
        <td> <%= page.published_at %> </td>
        <td> <%= page.priority %> </td>
        <td>
          <%= link_to page_show_path(page[:slug]) do%>
              <button type="button" class="btn btn-outline-primary btn-sm">Show</button>
          <% end %>
        </td>
        <td>
          <%= link_to edit_page_path(page[:slug]) do%>
              <button type="button" class="btn btn-outline-warning btn-sm">Edit</button>
          <% end %>
        </td>

        <td>
          <%= link_to page_path(page) ,method: :delete,data: { confirm: 'Are you sure?' } do %>
              <button type="button" class="btn btn-outline-danger btn-sm">Delete</button>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/page/new.html.erb
<%= render "partials/header" %>

<%= form_with scope: :page, url: page_index_path, local: true, html:{class:"col-md-8 offset-md-2"} do |form| %>
    <h1>Create a page</h1>
    <div class="form-group row">
      <%= form.label :title , class:"col-sm-2 col-form-label"%>
      <%= form.text_field :title, class:"col-sm-3 form-control", placeholder:"Title" %>
    </div>

    <div class="form-group row">
      <%= form.label :description, class:"col-sm-2 col-form-label" %>
      <%= form.text_field :description, class:"col-sm-3 form-control", placeholder:"Description in meta tag" %>
    </div>

    <div class="form-group row">
      <%= form.label :slug, class:"col-sm-2 col-form-label"%><br>
      <%= form.text_field :slug, class:"col-sm-3 form-control", placeholder:"URL" %>
    </div>

    <div class="form-group row">
      <%= form.label :h1, class:"col-sm-2 col-form-label"%><br>
      <%= form.text_field :h1, class:"col-sm-3 form-control", placeholder:"Article title" %>
    </div>

    <div class="form-group">

      <%= form.label :content, class:"col-sm-2 col-form-label"%>
      <%= form.text_area :content, class:"form-control", id:"editor", rows:"10" %>
    </div>

    <div class="form-group">
      <%= form.label :published_at %><br>
      <div class="form-group row">
        <%= form.label :Date, class:"col-sm-2 col-form-label"%><br>
        <%= form.text_field :published_at_date, data: {provide: 'datepicker'},:value=>Date.today.strftime('%Y-%m-%d'), class:"datepicker col-sm-3 form-control", placeholder:"2017-02-28"%>

      </div>
      <div class="form-group row">
        <%= form.label :Time, class:"col-sm-2 col-form-label"%><br>
        <%= form.text_field :published_at_hour, class:"col-sm-3 form-control", placeholder:"23:59"%>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :priority, class:"col-sm-2 col-form-label"%><br>
      <%= form.text_field :priority, class:"col-sm-3 form-control" %>
    </div>

    <p>
      <%= form.submit 'Save', class:"btn btn-primary" %>
    </p>

<% end %>

app/views/page/show.html.erb
<% content_for :title, @page[:title] %>
<% content_for :description, @page[:description] %>


<%= render "partials/header" %>

<h1 class="col-md-1 offset-md-5 row"><%= @page[:h1] %></h1>

<div class="content"> <%= @page[:content].html_safe %> </div>

<div class="col-md-4 offset-md-4 row">
  <div class="col-md-2 offset-md-1">
    <%= link_to edit_page_path(@page[:slug]) do%>
        <button type="button" class="btn btn-outline-warning btn-sm">Edit</button>
    <% end %>

  </div>

  <div class="col-md-2 offset-md-1">
    <%= link_to page_path(@page) ,method: :delete,data: { confirm: 'Are you sure?' } do %>
        <button type="button" class="btn btn-outline-danger btn-sm">Delete</button>
    <% end %>
  </div>
</div>

app/views/partials/_header.html.erb
<div id="header">


  <%= link_to root_path do%>
      <div class="header1 links">Home</div>
  <% end %>

  <%= link_to new_page_path do%>
      <div class="header2 links"> Create new page</div>
  <% end %>

</div>

<!--<div class="col-md-8 offset-md-2">-->
  <!--<% flash.each do |key, message| %>-->
      <!--<% message.each do |msg| %>-->
          <!--<p class="<%= key %>"><%= msg %></p>-->
      <!--<% end %>-->
  <!--<% end %>-->
<!--</div>-->